name: "Run the E2E test on kind"
on:
  push:
  pull_request:
    # Do not run when the change only includes these directories.
    paths-ignore:
      - "site/**"
      - "design/**"
jobs:
  # Build the Velero CLI and image once for all Kubernetes versions, and cache it so the fan-out workers can get it.

  # Run E2E test against all kubernetes versions on kind
  run-e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          # doesn't cover 1.15 as 1.15 doesn't support "apiextensions.k8s.io/v1" that is needed for the case
          #- 1.15.12
          - 1.16.15
          - 1.17.17
          - 1.18.15
          - 1.19.7
          - 1.20.2
          - 1.21.1
      fail-fast: false
    steps:
      - uses: engineerd/setup-kind@v0.5.0
        with:
          image: "kindest/node:v${{ matrix.k8s }}"
      - name: Run E2E test
        run: |
          docker ps || true
          kubectl get node -o wide || true
          docker logs kind-control-plane || true