name: build-image

on:
  push:
    branches: [ main ]
    paths:
    - 'hack/build-image/Dockerfile'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Build
      run: make a

    # Only try to publish the container image from the root repo; forks don't have permission to do so and will always get failures.
    - name: Publish container image
      if: github.repository == 'vmware-tanzu/velero'
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
       
        make push-build-image
